"""Hand-authored seed batch — generated BY the agent, not by a remote model.

Bob's instruction (2026-09-27): "Generate the small batch urself, ur the llm".

Everything in SEEDS below was written directly rather than fetched from the free
OpenRouter pool. The API detour was a mistake: replies truncated at max_tokens so
every parse returned nothing, and raising concurrency made the TLS handshakes hang.
None of that was necessary.

Each entry is a realistic OCULUS state followed by the correct option key. Labels are
balanced by construction because the entries are grouped per option - the balance
problem the brief warns about (a generator drifting to the majority branch) cannot
happen when a human/agent writes each branch deliberately.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import data_harvester as dh  # noqa: E402

# ── D1.1.1 genome_promote_verdict ────────────────────────────────────────────
# promote_to_oos / reject / needs_more_generations / quarantine
D1_1_1 = {
    "promote_to_oos": [
        "genome g4471, generation 12: in-sample Sharpe 2.31 over 1,480 trades, out-of-sample Sharpe 2.18 on a held-out 30% window, max drawdown 7.4%.",
        "EURUSD 30m lineage 88: IS profit factor 1.92, OOS profit factor 1.87, 2,204 trades, both windows positive for 6 consecutive months.",
        "BTCUSDT 5m variant 1203: IS return 41.2%, OOS return 38.9%, ulcer index 0.041, deflated Sharpe 1.94 after 240 trials.",
        "AAPL 1d genome 77b: IS Calmar 1.81, OOS Calmar 1.76, 388 trades, information ratio 0.62 and stable across both windows.",
        "NQ 2h lineage 512: IS Sharpe 1.88, OOS Sharpe 1.91, 911 trades, no single trade over 3.1% of total profit.",
        "genome m2210 gen 19: IS hit rate 58.4% on 1,102 trades, OOS hit rate 57.1%, profit factor within 4% across both windows.",
        "GBPUSD 30m g9004: IS expectancy 0.0031, OOS expectancy 0.0029, 1,870 trades, drawdown within 1.2pp between windows.",
        "ETHUSDT 1h lineage 331: IS Sharpe 2.02, OOS Sharpe 1.97, 640 trades, and it beats buy-and-hold on both windows by 12pp and 11pp.",
        "USDJPY 4h genome 155: IS profit factor 2.11, OOS 2.04, 402 trades, deflated Sharpe 1.71 across 180 trials, drawdown 6.9%.",
        "genome t8812 gen 22: IS return 27.4%, OOS 26.1%, 1,344 trades, ulcer index unchanged between windows at 0.036.",
        "SPY 1d variant 4402: IS Sharpe 1.74, OOS 1.70, 502 trades, and OOS was measured on three separate held-out folds all positive.",
        "genome k3301 gen 8: IS fitness 0.71, OOS fitness 0.69, 980 trades, consistency score 0.94 with no regime dependence detected.",
    ],
    "reject": [
        "genome g1120 gen 9: in-sample Sharpe 2.62 but out-of-sample Sharpe 0.11 on the held-out window, 1,204 trades, drawdown 22.4%.",
        "EURAUD 15m lineage 77: IS profit factor 2.41, OOS profit factor 0.88, 2,810 trades, edge disappears entirely out of sample.",
        "genome b9902 gen 14: IS return 58.1%, OOS return -7.3%, 1,102 trades - the in-sample curve is not reproducible.",
        "DOGEUSDT 5m variant 61: IS Sharpe 3.10, OOS Sharpe -0.42, 4,120 trades, almost certainly fitted to noise on a thin asset.",
        "genome r4410 gen 6: IS fitness 0.88, OOS fitness 0.09, 744 trades, below the survival threshold in the second window.",
        "CL 1h lineage 2201: IS expectancy 0.0089, OOS expectancy -0.0014, 1,660 trades, both windows disagree on sign.",
        "genome h7730 gen 11: IS profit factor 1.94 on 3,011 trades, OOS 0.79 on 402 trades - the trade count itself collapses out of sample.",
        "XRPUSDT 1h variant 914: IS Sharpe 2.44, OOS 0.21, 2,205 trades, deflated Sharpe 0.31 after 420 trials.",
        "genome p5520 gen 17: IS return 33.8%, OOS -2.1%, 1,909 trades, max drawdown 31.2% in the second window.",
        "AUDUSD 30m lineage 88: IS Calmar 1.62, OOS Calmar -0.11, 1,470 trades, information ratio negative out of sample.",
        "genome w2210 gen 5: IS hit rate 61.2% on 2,140 trades, OOS hit rate 47.8% - below a coin flip once costs are applied.",
        "GC 4h variant 3308: IS Sharpe 1.91, OOS 0.14, 388 trades, and the OOS window covers the same regime as in-sample.",
    ],
    "needs_more_generations": [
        "genome n1110 gen 2: IS fitness 0.41, OOS 0.39, only 180 trades - on the right track but far short of convergence.",
        "genome q8890 gen 1: IS fitness 0.22, OOS 0.24, 90 trades, first generation of a new lineage with no depth yet.",
        "lineage 604 gen 3: fitness climbed 0.18 to 0.44 to 0.51 across three generations, still rising, 620 trades.",
        "genome c2211 gen 2: IS fitness 0.38, population rank 74 of 200, improving 0.06 per generation, 410 trades.",
        "genome d1170 gen 4: fitness 0.47 with a positive slope across the last three generations, 880 trades, not yet at the survival bar.",
        "lineage 771 gen 1: fitness 0.19, 140 trades, too early to judge - the first generation is never converged.",
        "genome e5510 gen 3: IS 0.36, OOS 0.33, fitness rising 0.05 per generation, 502 trades, viability not yet established.",
        "genome f9901 gen 2: 640 trades, fitness 0.43, mutation still producing variance above noise in every generation.",
        "lineage 228 gen 5: fitness 0.52 flat for two generations, 1,010 trades, undecided between further search and rejection.",
        "genome a3340 gen 3: fitness 0.40, 780 trades, gains in the last three generations, no plateau observed yet.",
        "genome z7712 gen 1: fitness 0.25, 210 trades, freshly seeded lineage with one generation of evidence.",
        "lineage 915 gen 4: fitness trend positive at 0.49 with 1,140 trades, statistically alive but not yet convincing.",
    ],
    "quarantine": [
        "genome g5510 gen 7: IS Sharpe 2.44, OOS Sharpe 2.41, but 1,902 trades and only 4 distinct entry conditions - suspiciously concentrated but performing.",
        "genome y1120 gen 9: IS profit factor 1.88, OOS 1.84, 2,204 trades, yet 71% of profit comes from 3 days in the window.",
        "EURUSD 30m lineage 440: IS and OOS both positive at Sharpe 1.9 and 1.8, but 4,100 trades is far above the asset's usual count - the cost model may be wrong.",
        "genome u8890 gen 12: IS fitness 0.66, OOS 0.69 - OOS ABOVE IS, with 1,340 trades, which is itself a red flag for a leak.",
        "genome i2210 gen 6: IS Sharpe 2.01, OOS 1.96, 1,120 trades, but the trade timestamp distribution is non-uniform in a way the sanity check flags.",
        "genome o3340 gen 10: metrics strong in both windows at 0.71 and 0.68, 1,880 trades, but the feature vector matches a retired leaky set.",
        "genome l7710 gen 8: IS 1.84, OOS 1.79, 1,402 trades, yet the pipeline reported the OOS window as 2 days shorter than configured.",
        "lineage 512 gen 13: IS 0.74, OOS 0.72, 2,010 trades, but the data-quality check failed on 0.4% of bars in the OOS window.",
        "genome s9900 gen 5: both windows positive at Sharpe 2.1, 900 trades, but the sign of one indicator is inverted against its own definition.",
        "genome v1101 gen 11: IS 0.69, OOS 0.70, 1,610 trades, yet the equity curve shows an unexplained step change mid-window.",
        "genome x4420 gen 7: strong at 0.75 and 0.73 on 1,290 trades, but the genome references a parameter slot that no longer exists in the schema.",
        "genome m3301 gen 9: IS 0.81, OOS 0.78, 1,140 trades, and the same genome id appears twice in the island buffer with different fitness values.",
    ],
}

# ── D1.1.2 survival_threshold ────────────────────────────────────────────────
# cleared / below / borderline_review
D1_1_2 = {
    "cleared": [
        "genome g2201, generation 14: fitness 0.640 against a survival threshold of 0.58 for this generation, 1,204 trades.",
        "lineage 88 gen 11: fitness 0.712 versus a required 0.66, 1,880 trades, above the bar set for the eleventh generation.",
        "genome b5510 gen 6: fitness 0.521 against a threshold of 0.48, 902 trades, margin of 0.041.",
        "genome r7710 gen 9: fitness 0.688 versus 0.62 required, 1,340 trades, clears by 0.068.",
        "lineage 331 gen 16: fitness 0.741 against 0.70 for this generation, 2,010 trades.",
        "genome h1120 gen 4: fitness 0.462 against a 0.42 bar, 610 trades, above the line by 0.042.",
        "genome p8890 gen 12: fitness 0.702 versus 0.64 required, 1,470 trades, comfortably through.",
        "lineage 604 gen 8: fitness 0.611 against 0.56, 1,120 trades, margin 0.051.",
        "genome x2210 gen 15: fitness 0.766 against a 0.72 threshold, 2,240 trades.",
        "genome d3301 gen 7: fitness 0.548 versus a required 0.50, 788 trades, clears by 0.048.",
        "lineage 915 gen 13: fitness 0.694 against 0.64, 1,660 trades, above the bar.",
        "genome w4420 gen 5: fitness 0.487 against a 0.44 threshold, 540 trades, through by 0.047.",
    ],
    "below": [
        "genome q1120 gen 14: fitness 0.412 against a survival threshold of 0.58, 1,204 trades - well short.",
        "lineage 2201 gen 11: fitness 0.398 versus a required 0.66, 1,880 trades, below by 0.262.",
        "genome n5510 gen 6: fitness 0.291 against a threshold of 0.48, 902 trades, fails by a wide margin.",
        "genome y7710 gen 9: fitness 0.402 versus 0.62 required, 1,340 trades, below the line.",
        "lineage 888 gen 16: fitness 0.511 against 0.70, 2,010 trades, short by 0.189.",
        "genome c1120 gen 4: fitness 0.238 against a 0.42 bar, 610 trades, clearly under.",
        "genome e8890 gen 12: fitness 0.377 versus 0.64 required, 1,470 trades, fails.",
        "lineage 604 gen 8: fitness 0.401 against 0.56, 1,120 trades, below by 0.159.",
        "genome k2210 gen 15: fitness 0.489 versus a 0.72 threshold, 2,240 trades, well short.",
        "genome t3301 gen 7: fitness 0.311 against a required 0.50, 788 trades, under the bar.",
        "lineage 771 gen 13: fitness 0.442 versus 0.64, 1,660 trades, fails the generation requirement.",
        "genome z4420 gen 5: fitness 0.276 against a 0.44 threshold, 540 trades, below.",
    ],
    "borderline_review": [
        "genome m1120 gen 14: fitness 0.579 against a survival threshold of 0.58, 1,204 trades - over by 0.001, effectively on the line.",
        "lineage 3301 gen 11: fitness 0.658 versus 0.66 required, 1,880 trades, short by 0.002.",
        "genome v5510 gen 6: fitness 0.481 against a 0.48 bar, 902 trades, clears by 0.001.",
        "genome j7710 gen 9: fitness 0.619 versus 0.62 required, 1,340 trades, short by 0.001.",
        "lineage 221 gen 16: fitness 0.699 against 0.70, 2,010 trades, under by 0.001 - the call changes with rounding.",
        "genome s1120 gen 4: fitness 0.421 against a 0.42 bar, 610 trades, over by 0.001.",
        "genome u8890 gen 12: fitness 0.638 versus 0.64 required, 1,470 trades, short by 0.002.",
        "lineage 909 gen 8: fitness 0.559 against 0.56, 1,120 trades, over by 0.001.",
        "genome i2210 gen 15: fitness 0.719 versus a 0.72 threshold, 2,240 trades, short by 0.001.",
        "genome o3301 gen 7: fitness 0.499 against a required 0.50, 788 trades, under by 0.001.",
        "lineage 415 gen 13: fitness 0.641 versus 0.64, 1,660 trades, clears by 0.001.",
        "genome l4420 gen 5: fitness 0.439 against a 0.44 threshold, 540 trades, short by 0.001.",
    ],
}

SEEDS = {
    "D1.1.1": {"question": "What should happen to the mutated genome described in `state` next?",
               "data": D1_1_1},
    "D1.1.2": {"question": "Did the genome in `state` clear the survival threshold for its generation?",
               "data": D1_1_2},
}


def main() -> None:
    tax = json.load(open(os.path.join(HERE, "taxonomy_map.json")))
    by_id = {l["id"]: l for d in tax["domains"] for sr in d["sub_routers"] for l in sr["leaves"]}
    out_dir = os.path.join(HERE, "datasets")
    os.makedirs(out_dir, exist_ok=True)
    grand = 0
    for lid, spec in SEEDS.items():
        leaf = by_id[lid]
        opts = leaf["options"]
        rows = []
        for label, states in spec["data"].items():
            assert label in opts, f"{lid}: {label!r} is not a frozen option key"
            for st in states:
                rows.append({"state": st, "label": label, "option_text": opts[label]})
        counts = {k: sum(1 for r in rows if r["label"] == k) for k in opts}
        # Balance is structural here: any option with no authored examples is a gap.
        assert all(counts[k] > 0 for k in opts), f"{lid}: an option got no examples: {counts}"
        for b in range(0, len(rows), dh.BATCH_SIZE):
            dh.write_batch(lid, b // dh.BATCH_SIZE, rows[b:b + dh.BATCH_SIZE])
        json.dump({"id": lid, "kind": "leaf", "question": leaf["question"],
                   "options": opts, "label_counts": counts, "samples": rows},
                  open(os.path.join(out_dir, f"{lid}.json"), "w"), indent=2)
        grand += len(rows)
        print(f"  {lid}  {len(rows):4d} samples  balance={min(counts.values())}/{max(counts.values())}  {counts}")
    print(f"  total authored: {grand}")


if __name__ == "__main__":
    main()
